//
// Generated file, do not edit! Created by opp_msgc 4.2 from applications/test/TestMessage.msg.
//

#ifndef _TESTMESSAGE_M_H_
#define _TESTMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include <TransportAddress.h>
// }}



/**
 * Enum generated from <tt>applications/test/TestMessage.msg</tt> by opp_msgc.
 * <pre>
 * enum MessageType 
 * {
 *     MYMSG_PING = 1;           
 *     MYMSG_PONG = 2;           
 * }
 * </pre>
 */
enum MessageType {
    MYMSG_PING = 1,
    MYMSG_PONG = 2
};

/**
 * Class generated from <tt>applications/test/TestMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet TestMessage 
 * {
 *     int type enum(MessageType);      
 *     TransportAddress senderAddress;  
 * }
 * </pre>
 */
class TestMessage : public ::cPacket
{
  protected:
    int type_var;
    TransportAddress senderAddress_var;

  private:
    void copy(const TestMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TestMessage&);

  public:
    TestMessage(const char *name=NULL, int kind=0);
    TestMessage(const TestMessage& other);
    virtual ~TestMessage();
    TestMessage& operator=(const TestMessage& other);
    virtual TestMessage *dup() const {return new TestMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getType() const;
    virtual void setType(int type);
    virtual TransportAddress& getSenderAddress();
    virtual const TransportAddress& getSenderAddress() const {return const_cast<TestMessage*>(this)->getSenderAddress();}
    virtual void setSenderAddress(const TransportAddress& senderAddress);
};

inline void doPacking(cCommBuffer *b, TestMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TestMessage& obj) {obj.parsimUnpack(b);}


#endif // _TESTMESSAGE_M_H_
